[package]
name = "gba"
version = "0.1.0"
authors = ["rodrifs"]
edition = "2018"

[dependencies]
byteorder = "1.3"
minifb = "0.16"

# [dependencies.gtk]
# version = "0.9.0"
# features = ["v3_16"]

# [dependencies.gio]
# version = "0.9.0"
# features = ["v2_44"]